// Copyright (C) 2024-2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Evidence runner for the pinned Wycheproof ML-DSA-65 repeated-hint case.
//!
//! This example is invoked only by the dedicated C2 evidence workflow. It has
//! no network/parser logic: the Python provenance gate authenticates and extracts
//! the upstream bytes first, then this runner asks Xenia's production verifier
//! boundary to evaluate them.

use std::env;
use std::fs;
use std::path::Path;

use xenia_handshake::{
    HandshakeManager, ML_DSA_65_PK_LEN, ML_DSA_65_SIG_LEN,
};

fn read_exact<const N: usize>(path: &Path, label: &str) -> [u8; N] {
    let bytes = fs::read(path).unwrap_or_else(|err| panic!("failed to read {label}: {err}"));
    bytes.try_into().unwrap_or_else(|bytes: Vec<u8>| {
        panic!("{label} must be exactly {N} bytes, found {}", bytes.len())
    })
}

fn main() {
    let args: Vec<String> = env::args().collect();
    assert_eq!(
        args.len(),
        4,
        "usage: verify_wycheproof_mldsa65_tc19 <public_key.bin> <message.bin> <signature.bin>"
    );

    // Positive control: prove this runner/provider path can accept a valid
    // signature generated by Xenia before asking it to reject the adversarial
    // upstream vector.
    let positive = HandshakeManager::from_identity_seeds([0x51; 32], [0x61; 32]);
    let positive_message = b"xenia-c2-positive-control";
    let positive_pk = positive.ml_dsa_public_key_bytes();
    let positive_sig = positive.sign_ml_dsa(positive_message);
    HandshakeManager::verify_ml_dsa(&positive_pk, positive_message, &positive_sig)
        .expect("Xenia-generated ML-DSA-65 positive control must verify");
    println!("positive control accepted");

    let public_key = read_exact::<ML_DSA_65_PK_LEN>(Path::new(&args[1]), "public key");
    let message = fs::read(&args[2]).expect("failed to read message");
    let signature = read_exact::<ML_DSA_65_SIG_LEN>(Path::new(&args[3]), "signature");

    let rejection = HandshakeManager::verify_ml_dsa(&public_key, &message, &signature)
        .expect_err("pinned Wycheproof tcId 19 repeated-hint signature must not verify");

    println!("tcId 19 rejected by Xenia verifier: {rejection}");
}
