#!/usr/bin/env bash
set -euo pipefail
# Generated by apply-normalization-execution.py.
# Review before running. This only reverses filesystem moves/archives, not Cargo.toml text edits.
cd "/srv/luminous-dynamics/xenia/xenia-peer"

mv -- "apps/sovereign-admin" "crates/sovereign-admin"
mv -- "apps/xenia-peer" "crates/xenia-peer"
mv -- "apps/xenia-viewer" "crates/xenia-viewer"
mv -- "_archive/normalization-v0.2/build-output/target" "target"
