// Copyright (c) 2026 Tristan Stoltz / Luminous Dynamics
// SPDX-License-Identifier: AGPL-3.0-or-later
//! Crypto-free canonical protocol for Xenia-authenticated bounded agent authority.
//!
//! This module deliberately contains no signing keys, network I/O, policy engine,
//! or agent runtime. It defines only the fixed semantic object that an authority
//! service may sign and that an execution environment may verify independently.

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Schema version for [`AgentCapabilityAuthorizationV1`].
pub const AGENT_CAPABILITY_AUTHORIZATION_SCHEMA_VERSION: u16 = 1;
/// Domain separator for the signed authorization message.
pub const AGENT_CAPABILITY_AUTHORIZATION_DOMAIN: &[u8] =
    b"xenia.agent-capability-authorization.v1\0";

/// Stable signature-suite identifier for the authenticated session transcript.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[repr(u8)]
pub enum TranscriptSignatureSuiteV1 {
    /// Ed25519 / RFC 8032.
    Ed25519Rfc8032 = 1,
    /// ML-DSA-65 / FIPS 204.
    MlDsa65Fips204 = 2,
    /// ML-DSA-87 / FIPS 204.
    MlDsa87Fips204 = 3,
}

/// Optional anti-rollback anchor for the agent runtime state that existed when
/// the authority decision was issued.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentCheckpointAnchorV1 {
    /// Monotonic checkpoint generation.
    pub sequence: u64,
    /// Commitment to the exact checkpoint generation.
    pub digest: [u8; 32],
}

/// Opaque, fixed-size authorization object signed by Xenia.
///
/// `capability_digest` is intentionally opaque to Xenia. In Symthaea it is the
/// exact commitment of a `CapabilityGrant`; other bounded agents may use a
/// different semantic capability object without changing this protocol.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentCapabilityAuthorizationV1 {
    /// Must equal [`AGENT_CAPABILITY_AUTHORIZATION_SCHEMA_VERSION`].
    pub schema_version: u16,
    /// Stable authorization identifier generated by the authority service.
    pub authorization_id: [u8; 16],
    /// Authenticated Xenia session UUID bytes.
    pub session_id: [u8; 16],
    /// Commitment to the canonical authenticated session transcript.
    pub session_transcript_hash: [u8; 32],
    /// Signature suite that authenticated the session transcript.
    pub session_signature_suite: TranscriptSignatureSuiteV1,
    /// Exact semantic capability commitment being authorized.
    pub capability_digest: [u8; 32],
    /// Exact workload/software identity allowed to exercise the capability.
    pub executor_workload_digest: [u8; 32],
    /// Monotonic authority epoch supplied by the bounded-agent domain.
    pub authority_epoch: u64,
    /// Earliest accepted wall-clock instant for this authorization.
    pub issued_at_unix_s: u64,
    /// Hard expiry. Must be strictly after `issued_at_unix_s`.
    pub expires_at_unix_s: u64,
    /// Replay/domain nonce. All-zero is invalid.
    pub nonce: [u8; 16],
    /// Xenia ledger frontier entry count at authorization time.
    pub ledger_entry_count: u64,
    /// Xenia ledger frontier hash at authorization time.
    pub ledger_head_hash: [u8; 32],
    /// Optional exact prior agent-runtime checkpoint anchor.
    pub prior_checkpoint: Option<AgentCheckpointAnchorV1>,
}

impl AgentCapabilityAuthorizationV1 {
    /// Validate only structural/canonical invariants. Cryptographic verification
    /// and policy freshness remain the caller's responsibility.
    pub fn validate(&self) -> Result<(), AgentCapabilityAuthorizationError> {
        if self.schema_version != AGENT_CAPABILITY_AUTHORIZATION_SCHEMA_VERSION {
            return Err(AgentCapabilityAuthorizationError::UnsupportedSchema);
        }
        if self.authorization_id == [0u8; 16] {
            return Err(AgentCapabilityAuthorizationError::ZeroAuthorizationId);
        }
        if self.session_id == [0u8; 16] {
            return Err(AgentCapabilityAuthorizationError::ZeroSessionId);
        }
        if self.session_transcript_hash == [0u8; 32] {
            return Err(AgentCapabilityAuthorizationError::ZeroSessionTranscriptHash);
        }
        if self.capability_digest == [0u8; 32] {
            return Err(AgentCapabilityAuthorizationError::ZeroCapabilityDigest);
        }
        if self.executor_workload_digest == [0u8; 32] {
            return Err(AgentCapabilityAuthorizationError::ZeroExecutorWorkloadDigest);
        }
        if self.expires_at_unix_s <= self.issued_at_unix_s {
            return Err(AgentCapabilityAuthorizationError::InvalidValidityWindow);
        }
        if self.nonce == [0u8; 16] {
            return Err(AgentCapabilityAuthorizationError::ZeroNonce);
        }
        if self.ledger_entry_count == 0 || self.ledger_head_hash == [0u8; 32] {
            return Err(AgentCapabilityAuthorizationError::MissingLedgerFrontier);
        }
        if self
            .prior_checkpoint
            .is_some_and(|anchor| anchor.digest == [0u8; 32])
        {
            return Err(AgentCapabilityAuthorizationError::ZeroCheckpointDigest);
        }
        Ok(())
    }

    /// Stable hand-written canonical message to sign.
    ///
    /// The format is not serde/bincode dependent. Any change to field order or
    /// encoding requires a new schema/domain version.
    pub fn canonical_message(&self) -> Result<Vec<u8>, AgentCapabilityAuthorizationError> {
        self.validate()?;
        let mut out = Vec::with_capacity(320);
        out.extend_from_slice(AGENT_CAPABILITY_AUTHORIZATION_DOMAIN);
        out.extend_from_slice(&self.schema_version.to_be_bytes());
        out.extend_from_slice(&self.authorization_id);
        out.extend_from_slice(&self.session_id);
        out.extend_from_slice(&self.session_transcript_hash);
        out.push(self.session_signature_suite as u8);
        out.extend_from_slice(&self.capability_digest);
        out.extend_from_slice(&self.executor_workload_digest);
        out.extend_from_slice(&self.authority_epoch.to_be_bytes());
        out.extend_from_slice(&self.issued_at_unix_s.to_be_bytes());
        out.extend_from_slice(&self.expires_at_unix_s.to_be_bytes());
        out.extend_from_slice(&self.nonce);
        out.extend_from_slice(&self.ledger_entry_count.to_be_bytes());
        out.extend_from_slice(&self.ledger_head_hash);
        match self.prior_checkpoint {
            None => out.push(0),
            Some(anchor) => {
                out.push(1);
                out.extend_from_slice(&anchor.sequence.to_be_bytes());
                out.extend_from_slice(&anchor.digest);
            }
        }
        Ok(out)
    }
}

/// Structural/canonical authorization failures.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum AgentCapabilityAuthorizationError {
    /// Unknown schema version.
    #[error("unsupported agent capability authorization schema")]
    UnsupportedSchema,
    /// Authorization identifier cannot be all zero.
    #[error("authorization id must not be zero")]
    ZeroAuthorizationId,
    /// Session identifier cannot be all zero.
    #[error("session id must not be zero")]
    ZeroSessionId,
    /// Session transcript commitment cannot be all zero.
    #[error("session transcript hash must not be zero")]
    ZeroSessionTranscriptHash,
    /// Semantic capability commitment cannot be all zero.
    #[error("capability digest must not be zero")]
    ZeroCapabilityDigest,
    /// Executor/workload commitment cannot be all zero.
    #[error("executor workload digest must not be zero")]
    ZeroExecutorWorkloadDigest,
    /// Expiry must be strictly after issuance.
    #[error("authorization validity window is invalid")]
    InvalidValidityWindow,
    /// Replay nonce cannot be all zero.
    #[error("authorization nonce must not be zero")]
    ZeroNonce,
    /// Authorizations must be tied to a non-genesis Xenia ledger frontier.
    #[error("authorization requires a non-empty Xenia ledger frontier")]
    MissingLedgerFrontier,
    /// Optional runtime checkpoint anchors must carry a non-zero digest.
    #[error("checkpoint digest must not be zero")]
    ZeroCheckpointDigest,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> AgentCapabilityAuthorizationV1 {
        AgentCapabilityAuthorizationV1 {
            schema_version: AGENT_CAPABILITY_AUTHORIZATION_SCHEMA_VERSION,
            authorization_id: [1; 16],
            session_id: [2; 16],
            session_transcript_hash: [3; 32],
            session_signature_suite: TranscriptSignatureSuiteV1::Ed25519Rfc8032,
            capability_digest: [4; 32],
            executor_workload_digest: [5; 32],
            authority_epoch: 7,
            issued_at_unix_s: 100,
            expires_at_unix_s: 160,
            nonce: [6; 16],
            ledger_entry_count: 12,
            ledger_head_hash: [7; 32],
            prior_checkpoint: Some(AgentCheckpointAnchorV1 {
                sequence: 9,
                digest: [8; 32],
            }),
        }
    }

    #[test]
    fn canonical_message_is_deterministic_and_sensitive() {
        let a = sample();
        let mut b = a.clone();
        assert_eq!(a.canonical_message().unwrap(), b.canonical_message().unwrap());
        b.executor_workload_digest[0] ^= 1;
        assert_ne!(a.canonical_message().unwrap(), b.canonical_message().unwrap());
    }

    #[test]
    fn zero_and_pre_genesis_bindings_fail_closed() {
        let mut value = sample();
        value.capability_digest = [0; 32];
        assert_eq!(
            value.validate(),
            Err(AgentCapabilityAuthorizationError::ZeroCapabilityDigest)
        );

        let mut value = sample();
        value.ledger_entry_count = 0;
        assert_eq!(
            value.validate(),
            Err(AgentCapabilityAuthorizationError::MissingLedgerFrontier)
        );
    }
}
