#!/usr/bin/env python3
"""Dry-run or apply the Xenia normalization execution plan.

This script is intentionally conservative:
- dry-run is the default;
- --apply is required for filesystem changes;
- existing targets are never overwritten;
- every applied run writes a JSON ledger and rollback shell script.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time
from typing import Any


def fail(message: str) -> None:
    print(f"FAIL: {message}", file=sys.stderr)
    raise SystemExit(1)


def run_plan(root: Path, output: Path) -> dict[str, Any]:
    script = root / "scripts" / "plan-normalization-execution.py"
    if not script.exists():
        fail("scripts/plan-normalization-execution.py not found")
    subprocess.run([sys.executable, str(script), str(root), "--output", str(output)], check=True)
    with output.open("r", encoding="utf-8") as f:
        return json.load(f)


def rel(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def ensure_under_root(root: Path, path: Path) -> None:
    try:
        path.resolve().relative_to(root.resolve())
    except ValueError:
        fail(f"path escapes root: {path}")


def move_path(root: Path, source_rel: str, target_rel: str) -> dict[str, Any]:
    source = root / source_rel
    target = root / target_rel
    ensure_under_root(root, source)
    ensure_under_root(root, target)
    if not source.exists():
        return {"status": "skipped", "reason": "source-missing", "source": source_rel, "target": target_rel}
    if target.exists():
        return {"status": "blocked", "reason": "target-exists", "source": source_rel, "target": target_rel}
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(source), str(target))
    return {"status": "moved", "source": source_rel, "target": target_rel}


def rewrite_cargo_member(root: Path, cargo_rel: str, old: str, new: str, apply: bool) -> dict[str, Any]:
    cargo = root / cargo_rel
    ensure_under_root(root, cargo)
    if not cargo.exists():
        return {"status": "skipped", "reason": "cargo-toml-missing", "cargo_toml": cargo_rel, "from": old, "to": new}
    text = cargo.read_text(encoding="utf-8")
    replacements = [
        (f'"{old}"', f'"{new}"'),
        (f"'{old}'", f"'{new}'"),
    ]
    changed = text
    count = 0
    for before, after in replacements:
        n = changed.count(before)
        changed = changed.replace(before, after)
        count += n
    if count == 0:
        return {"status": "unchanged", "reason": "member-not-found", "cargo_toml": cargo_rel, "from": old, "to": new}
    if apply:
        cargo.write_text(changed, encoding="utf-8")
    return {"status": "rewritten" if apply else "would-rewrite", "count": count, "cargo_toml": cargo_rel, "from": old, "to": new}


def rollback_line(action: dict[str, Any]) -> str | None:
    if action.get("status") != "moved":
        return None
    source = action["source"]
    target = action["target"]
    return f'mv -- {json.dumps(target)} {json.dumps(source)}'


def write_rollback(root: Path, applied: list[dict[str, Any]], rollback_path: Path) -> None:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by apply-normalization-execution.py.",
        "# Review before running. This only reverses filesystem moves/archives, not Cargo.toml text edits.",
        f"cd {json.dumps(str(root))}",
        "",
    ]
    for action in reversed(applied):
        line = rollback_line(action)
        if line:
            lines.append(line)
    lines.append("")
    rollback_path.parent.mkdir(parents=True, exist_ok=True)
    rollback_path.write_text("\n".join(lines), encoding="utf-8")
    rollback_path.chmod(0o755)


def main() -> int:
    parser = argparse.ArgumentParser(description="Dry-run/apply Xenia normalization execution.")
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--apply", action="store_true", help="actually move files and rewrite Cargo.toml members")
    parser.add_argument("--plan", default=None, help="existing plan JSON to use instead of generating one")
    parser.add_argument("--ledger", default=None, help="ledger path; default under _archive/normalization-v0.2")
    parser.add_argument("--rollback", default=None, help="rollback script path; default under _archive/normalization-v0.2")
    parser.add_argument("--skip-cargo-rewrite", action="store_true", help="move/archive only; do not rewrite Cargo.toml members")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    archive_dir = root / "_archive" / "normalization-v0.2"
    archive_dir.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    plan_path = Path(args.plan).resolve() if args.plan else archive_dir / f"execution-plan-{stamp}.json"
    ledger_path = Path(args.ledger).resolve() if args.ledger else archive_dir / f"execution-ledger-{stamp}.json"
    rollback_path = Path(args.rollback).resolve() if args.rollback else archive_dir / f"rollback-{stamp}.sh"

    if args.plan:
        with plan_path.open("r", encoding="utf-8") as f:
            plan = json.load(f)
    else:
        plan = run_plan(root, plan_path)

    applied: list[dict[str, Any]] = []
    blocked: list[dict[str, Any]] = []
    dry_run: list[dict[str, Any]] = []

    for action in plan.get("actions", []):
        kind = action.get("action")
        if kind in {"archive", "move"}:
            result = {"action": kind, **move_path(root, action["source"], action["target"])} if args.apply else {"action": kind, "status": "would-move", "source": action["source"], "target": action["target"]}
            if result.get("status") == "blocked":
                blocked.append(result)
            elif result.get("status") == "moved":
                applied.append(result)
            else:
                dry_run.append(result)
        elif kind == "rewrite_cargo_member" and not args.skip_cargo_rewrite:
            result = {"action": kind, **rewrite_cargo_member(root, action["cargo_toml"], action["from"], action["to"], args.apply)}
            if result.get("status") == "rewritten":
                applied.append(result)
            else:
                dry_run.append(result)
        else:
            dry_run.append({"action": kind, "status": "ignored", "raw": action})

    ledger = {
        "schema": "xenia.normalization.execution-ledger.v1",
        "root": str(root),
        "mode": "apply" if args.apply else "dry-run",
        "plan": str(plan_path),
        "ledger": str(ledger_path),
        "rollback": str(rollback_path) if args.apply else None,
        "applied_count": len(applied),
        "blocked_count": len(blocked),
        "dry_run_count": len(dry_run),
        "applied": applied,
        "blocked": blocked,
        "dry_run": dry_run,
    }
    ledger_path.parent.mkdir(parents=True, exist_ok=True)
    ledger_path.write_text(json.dumps(ledger, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    if args.apply:
        write_rollback(root, applied, rollback_path)

    print(json.dumps({"mode": ledger["mode"], "applied": len(applied), "blocked": len(blocked), "dry_run": len(dry_run), "ledger": str(ledger_path), "rollback": str(rollback_path) if args.apply else None}, indent=2, sort_keys=True))

    if blocked:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
