#!/usr/bin/env python3
"""No-Rust source contract for Xenia application lane recovery V17."""
from pathlib import Path
import hashlib, json, sys
ROOT=Path(__file__).resolve().parents[1]
def text(rel): return (ROOT/rel).read_text(encoding='utf-8')
checks=[]
def req(name,cond): checks.append((name,cond))
flow=text('crates/xenia-peer-core/src/producer_flow.rs')
viewer=text('apps/xenia-viewer/src/main.rs')
gui=text('apps/xenia-viewer/src/gui.rs')
daemon=text('apps/xenia-peer/src/main.rs')
mobile=text('crates/xenia-mobile-ffi/src/engine.rs')
ffi=text('crates/xenia-mobile-ffi/src/lib.rs')
jni=text('apps/xenia-viewer-android/src/main/cpp/xenia_jni.c')
req('audio_v3_policy', 'pub const DESKTOP_AUDIO_PLAYBACK_V3' in flow and 'overflow: ProducerOverflowPolicy::DropOldest' in flow)
req('audio_same_bound', 'capacity: DESKTOP_AUDIO_LATENCY_V1.ingress_capacity_frames' in flow)
req('fresh_audio_queue', 'struct FreshAudioQueue' in viewer and 'frames.pop_front();' in viewer and 'frames.push_back(frame);' in viewer)
req('viewer_uses_v3', 'DESKTOP_AUDIO_PLAYBACK_V3.capacity' in viewer)
req('gui_drains_fresh_queue', 'while let Some(frame) = queue.pop_front()' in gui)
req('pressure_counters', 'pub struct LanePressureCountersV1' in flow and 'pub struct LanePressureSnapshotV1' in flow)
req('audio_pressure_wired', 'record_dropped_superseded' in viewer)
req('video_stale_counted', 'video_pressure.record_stale()' in daemon)
req('video_deadline_counted', 'video_pressure.record_fatal_deadline()' in daemon)
req('owned_permit_reservation', 'try_reserve_owned()' in mobile and 'mpsc::OwnedPermit<FileTransferCommand>' in mobile)
req('reservation_ttl', 'FILE_TRANSFER_RESERVATION_TTL_MS: u64 = 30_000' in mobile and 'tokio::time::sleep' in mobile)
req('reservation_exact_len', 'ReservationSizeMismatch' in mobile and 'data.len() != reservation.expected_len' in mobile)
req('reservation_pre_copy_length_check', 'pub fn check_file_transfer_reservation' in mobile and ('reservation.expected_len != data_len' in mobile or 'expected_len != data_len' in mobile))
req('reservation_cancel', 'pub fn cancel_file_transfer_reservation' in mobile)
req('engine_drop_releases', 'reservations.clear();' in mobile and 'self._task.abort();' in mobile)
req('ffi_reserve', 'pub unsafe extern "C" fn xenia_reserve_send_file' in ffi)
req('ffi_commit', 'pub unsafe extern "C" fn xenia_commit_send_file' in ffi)
req('ffi_commit_checks_before_copy', ffi.find('check_file_transfer_reservation(token, data_len)') < ffi.find('std::slice::from_raw_parts(data, data_len)'))
req('ffi_cancel', 'pub extern "C" fn xenia_cancel_send_file_reservation' in ffi)
req('ffi_new_statuses', 'XENIA_SEND_FILE_INVALID_RESERVATION: i32 = 6' in ffi and 'XENIA_SEND_FILE_RESERVATION_SIZE_MISMATCH: i32 = 7' in ffi)
reserve=jni.find('xenia_reserve_send_file(')
copy=jni.find('GetByteArrayElements(env, data')
commit=jni.find('int32_t status = xenia_commit_send_file(')
req('jni_reserve_before_copy', reserve!=-1 and copy!=-1 and reserve<copy)
req('jni_commit_after_copy', copy!=-1 and commit!=-1 and copy<commit)
req('jni_cancel_on_copy_failure', 'xenia_cancel_send_file_reservation' in jni)
vector=json.loads((ROOT/'docs/security/XENIA_APPLICATION_LANE_RECOVERY_V17_VECTOR.json').read_text())
expected=vector.pop('canonical_sha256')
canonical=json.dumps(vector,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()
req('vector_sha256', hashlib.sha256(canonical).hexdigest()==expected)
req('vector_audio_drop_oldest', vector['desktop_audio']['overflow']=='drop-oldest')
req('vector_reservation', vector['mobile_file_reservation']['pre_copy_reservation'] is True)
req('vector_ttl', vector['mobile_file_reservation']['reservation_ttl_ms']==30000)
failed=[n for n,o in checks if not o]
for n,o in checks: print(f"{'PASS' if o else 'FAIL'} {n}")
if failed:
    print('application lane recovery V17 source contract FAILED: '+', '.join(failed),file=sys.stderr)
    raise SystemExit(1)
print(f'application lane recovery V17 source contract passed: checks={len(checks)}')
