#!/usr/bin/env python3
from pathlib import Path
import hashlib,json,re
root=Path(__file__).resolve().parents[1]
engine=(root/'crates/xenia-mobile-ffi/src/engine.rs').read_text()
ffi=(root/'crates/xenia-mobile-ffi/src/lib.rs').read_text()
jni=(root/'apps/xenia-viewer-android/src/main/cpp/xenia_jni.c').read_text()
bindings=(root/'apps/xenia-viewer-android/src/main/kotlin/io/luminousdynamics/xenia/NativeBindings.kt').read_text()
session=(root/'apps/xenia-viewer-android/src/main/kotlin/io/luminousdynamics/xenia/XeniaSession.kt').read_text()
activity=(root/'apps/xenia-viewer-android/src/main/kotlin/io/luminousdynamics/xenia/XeniaViewerActivity.kt').read_text()
cargo=(root/'crates/xenia-mobile-ffi/Cargo.toml').read_text()
vector=json.loads((root/'docs/security/XENIA_APPLICATION_FILE_STAGING_V20_VECTOR.json').read_text())
checks=[]
def req(name,cond):
    if not cond: raise SystemExit(f'FAIL {name}')
    checks.append(name)
req('tokio_fs_feature','tokio = { workspace = true, features = [\"fs\"] }' in cargo)
req('stream_lease','FILE_TRANSFER_STREAM_LEASE_MS: u64 = 5 * 60_000' in engine)
req('paused_stream_expiry_test','staged_stream_expiry_removes_partial_file_and_restores_capacity' in engine and '#[tokio::test(start_paused = true)]' in engine)
req('stream_upload','struct FileTransferStreamUpload' in engine)
req('staged_command','SendStagedFile' in engine)
req('incremental_blake3','stream.hasher.update(bytes)' in engine)
req('app_private_staging','outbound-staging' in engine and 'create_new(true)' in engine)
req('bounded_append','MOBILE_FILE_TRANSFER_MAX_BYTES_V1' in engine and 'checked_add(bytes.len())' in engine)
req('staged_tokio_read','tokio::fs::File::open(path)' in engine and 'FILE_TRANSFER_CHUNK_SIZE' in engine)
req('staged_cleanup','std::fs::remove_file(path)' in engine)
req('snapshot_v2_engine','FileTransferAdmissionSnapshotV2' in engine and 'active_stream_bytes' in engine)
req('snapshot_v2_ffi','XeniaFileTransferAdmissionSnapshotV2' in ffi)
req('snapshot_v2_jni','NativeBindings_fileTransferAdmissionSnapshotV2' in jni)
req('snapshot_v2_kotlin','FileTransferAdmissionSnapshotV2' in session)
req('ffi_stream_begin','xenia_begin_send_file_stream' in ffi and 'xenia_begin_send_file_stream' in jni)
req('ffi_stream_append','xenia_append_send_file_stream' in ffi and 'xenia_append_send_file_stream' in jni)
req('ffi_stream_finish','xenia_finish_send_file_stream' in ffi and 'xenia_finish_send_file_stream' in jni)
req('ffi_stream_cancel','xenia_cancel_send_file_stream' in ffi and 'xenia_cancel_send_file_stream' in jni)
req('io_status_rust','XENIA_SEND_FILE_IO_ERROR: i32 = 8;' in ffi)
req('io_status_c',re.search(r'XENIA_SEND_FILE_IO_ERROR\s*=\s*8\b',jni) is not None)
req('io_status_kotlin','SEND_FILE_IO_ERROR: Int = 8' in bindings and 'IO_ERROR' in session)
req('kotlin_64k','FILE_STREAM_CHUNK_BYTES = 64 * 1024' in session)
req('kotlin_stream_api','fun trySendFileStream' in session and 'appendSendFileStream' in session)
req('picker_no_readbytes','readBytes()' not in activity)
req('picker_streams','streamPickedFile' in activity and 'trySendFileStream' in activity)
req('unknown_length','expectedLen ?: -1L' in session and 'expected_len == u64::MAX' in ffi)
req('legacy_retained','fun trySendFile(name: String, data: ByteArray)' in session)
expected=vector.pop('canonical_sha256')
canonical=json.dumps(vector,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()
req('vector_sha',hashlib.sha256(canonical).hexdigest()==expected)
req('vector_wire_unchanged',vector['wire_protocol_changed'] is False)
req('vector_disk_bound',vector['max_staged_disk_bytes']==3*100*1024*1024)
req('vector_chunk',vector['java_jni_chunk_bytes']==64*1024==vector['wire_chunk_bytes'])
print(f'application file staging V20 source contract passed: {len(checks)} checks')
