#!/usr/bin/env bash
set -u -o pipefail

ROOT="${1:-.}"
OUT="${2:-_archive/ci-artifacts}"
ROOT="$(cd "$ROOT" && pwd)"
OUT_ABS="$OUT"
case "$OUT_ABS" in
  /*) ;;
  *) OUT_ABS="$ROOT/$OUT_ABS" ;;
esac
mkdir -p "$OUT_ABS/logs"

run_and_capture() {
  local name="$1"
  shift
  if [ ! -x "$ROOT/$1" ]; then
    echo "[ci-artifacts] skipping $name; missing executable: $1"
    echo "127" >"$OUT_ABS/logs/$name.exit"
    echo "missing executable: $1" >"$OUT_ABS/logs/$name.log"
    return 0
  fi
  echo "[ci-artifacts] running $name: $*"
  (cd "$ROOT" && "$@") >"$OUT_ABS/logs/$name.log" 2>&1
  local code=$?
  echo "$code" >"$OUT_ABS/logs/$name.exit"
  if [ "$code" -ne 0 ]; then
    echo "[ci-artifacts] $name exited $code; log: $OUT_ABS/logs/$name.log"
  fi
  return 0
}

run_and_capture hygiene scripts/xenia-hygiene-audit.sh .
run_and_capture policy scripts/check-xenia-policy.py .
run_and_capture release scripts/check-release-readiness.py .
run_and_capture secure-defaults scripts/check-secure-defaults.py .
run_and_capture codeowners scripts/check-codeowners.py .
run_and_capture normalization scripts/check-normalization-plan.py .
run_and_capture cargo-boundaries scripts/check-cargo-boundaries.py .
run_and_capture consent-coverage scripts/check-consent-coverage.py . --json "$OUT_ABS/consent-coverage.json"
run_and_capture fix-tickets scripts/generate-fix-tickets.py . --markdown "$OUT_ABS/fix-tickets.md" --json "$OUT_ABS/fix-tickets.json"

if [ -x "$ROOT/scripts/collect-xenia-metrics.py" ]; then
  echo "[ci-artifacts] running metrics"
  (cd "$ROOT" && scripts/collect-xenia-metrics.py .) >"$OUT_ABS/metrics.json" 2>"$OUT_ABS/logs/metrics.stderr.log"
  echo "$?" >"$OUT_ABS/logs/metrics.exit"
else
  echo "127" >"$OUT_ABS/logs/metrics.exit"
  echo "missing executable: scripts/collect-xenia-metrics.py" >"$OUT_ABS/logs/metrics.stderr.log"
fi

if [ -x "$ROOT/scripts/generate-release-dashboard.py" ]; then
  run_and_capture dashboard scripts/generate-release-dashboard.py . --markdown "$OUT_ABS/release-dashboard.md" --json "$OUT_ABS/release-dashboard.json"
fi

if [ -x "$ROOT/scripts/xenia-agent-handoff-report.sh" ]; then
  run_and_capture handoff scripts/xenia-agent-handoff-report.sh . "$OUT_ABS/agent-handoff.md"
fi

cat >"$OUT_ABS/README.md" <<EOF
# Xenia CI Artifacts

Generated by \`scripts/ci-collect-artifacts.sh\`.

Important outputs:

- \`release-dashboard.md\`
- \`fix-tickets.md\`
- \`agent-handoff.md\`
- \`metrics.json\`
- \`consent-coverage.json\`
- \`logs/*.log\`
- \`logs/*.exit\`

A failed or skipped check can still produce useful evidence. Review the matching
log and exit-code file before rerunning or changing policy.
EOF

echo "[ci-artifacts] wrote $OUT_ABS"
